[dependencies]
aur_helper = "paru"
packages = [
  "stow",
  "i3-wm",
  "alacritty",
  # "fish",
  "mpv",
  "neovim",
  "picom",
  "polybar",
  # "rofi",
  "fcitx5-im",
  "fcitx5-rime",
  "dex",
  "feh",
  "sing-box",
  "autotiling-rs",
  "steam",
  "openrgb",
  "npm",
  "rustup",
  "sccache",
  "go",
  "uv",
  "firefox-developer-edition",
  "yazi",
  "flameshot",
  "fzf",
  "zoxide",
  "fastfetch",
  "ttf-jetbrains-mono-nerd",
  "ttf-ms-win11-auto-zh_cn",
  "noto-fonts-emoji",
  "ttf-pingfang-git",
  # "zellij",
  "tealdeer",
  "tmux",
  "eza",
  "ripgrep",
  "fd",
  "ueberzugpp",
  "rust-analyzer",
  "clang",
  "gdb",
  # "xautocfg",
  "atuin",

  "zsh",
  "zsh-autosuggestions",
  "zsh-fast-syntax-highlighting",
  "zsh-history-substring-search",
  "zsh-theme-powerlevel10k-git",
  "zsh-completions",
]

[softlink]
alacritty = ""
dunst = ""
# fish = "" # deprecated, replaced by zsh
fontconfig = ""
i3 = ""
mpv = ""
nvim = ""
picom = ""
polybar = ""
# rofi = "" # deprecated, replaced by ./i3/scripts/fzfmenu.py
fcitx5 = "~/.local/share/"
# zellij = "" # deprecated, replaced by tmux
tmux = ""
yazi = ""
# xautocfg = ""
pipewire = ""
paru = ""
zsh = ""
