#!/usr/bin/env bash

Date=$(date +"%Y%m%d-%H%M")

echo "cleaning older snapshots..."
if [[ -n "$(btrfs subvolume list / | grep autosnap-)" ]]; then
  btrfs subvolume delete /autosnap-*
fi

echo "creating new snapshots..."
btrfs subvolume snapshot /home/ /autosnap-home-$Date
btrfs subvolume snapshot / /autosnap-root-$Date
