[[plugins]]
name = "app_launcher"
description = "Launch applications"
prefix = ""
picker = "fd -d2 -L '\\.app$' /Applications $HOME/Applications /System/Applications -x echo {/} | cut -d '.' -f1"
runner = "open -a '{}'"
background = true

[[plugins]]
name = "plugins-list"
description = "list all plugins"
prefix = "ls "
picker = "fzfmenu -l"
runner = "echo '{}'"

[[plugins]]
name = "focus"
description = "focus specific window"
prefix = "f "
picker = "hs $HOME/.config/fzfmenu/plugins/focus/picker.lua"
runner = "hs $HOME/.config/fzfmenu/plugins/focus/runner.lua '{}'"
background = true

[[plugins]]
name = "brotab"
description = "Activate tab using brotab"
prefix = "b "
picker = "python3 ~/.config/fzfmenu/plugins/brotab/brotab.py picker"
runner = "python3 ~/.config/fzfmenu/plugins/brotab/brotab.py runner"
background = true

[[plugins]]
name = "killer"
description = "Find and terminate running processes."
prefix = "kl "
picker = 'pgrep -li "$FZFMENU_INPUT"'
runner = 'echo "$FZFMENU_OUTPUT" | cut -d " " -f1 | xargs kill -9'
dynamic = true
background = true
