#!/bin/env python

import os
import subprocess
import sys


def main():
    argv = sys.argv
    _target = os.getcwd() if len(argv) == 1 else argv[1]
    target = os.path.abspath(_target)
    editor = os.environ["EDITOR"]
    if (
        not os.path.exists(target)
        and os.access(os.path.dirname(target), os.W_OK)
        or os.access(target, os.W_OK)
    ):
        subprocess.run(f"{editor} {target}", shell=True)
    else:
        subprocess.run(f"sudo -E {editor} {target}", shell=True)


if __name__ == "__main__":
    main()
