#!/bin/env python

import os
import sys


def main():
    argv = sys.argv
    _target = os.getcwd() if len(argv) == 1 else argv[-1]
    target = os.path.abspath(_target)
    flags = " ".join(argv[1:-1])
    editor = os.environ["EDITOR"]
    if (
        not os.path.exists(target)
        and os.access(os.path.dirname(target), os.W_OK)
        or os.access(target, os.W_OK)
    ):
        os.execl("/bin/sh", "sh", "-c", f"{editor} {flags} {target}")
    else:
        os.execl("/bin/sh", "sh", "-c", f"sudo -E {editor} {flags} {target}")


if __name__ == "__main__":
    main()
