ura.hook.set("prepare", function()
  ura.fn.set_env("XDG_CURRENT_DESKTOP", "sway")
  ura.fn.set_env("XDG_SESSION_TYPE", "wayland")
  ura.fn.set_env("WLR_RENDERER", "gles2")
  ura.fn.set_env("WLR_NO_HARDWARE_CURSORS", "0")
  ura.fn.set_env("LIBVA_DRIVER_NAME", "nvidia")
  ura.fn.set_env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
end)

ura.hook.set("ready", function()
  ura.fn.set_env("DISPLAY", ":0")
  ura.api.spawn("xwayland-satellite")
  ura.api.spawn("pegboard -i ~/.config/ura/assets/bg.jpg")
  ura.api.spawn("waybar")
  ura.api.spawn("openrgb --startminimized -p default")
  ura.api.spawn("sing-box run -c $HOME/.config/sing-box/config.yaml -D $HOME/.config/sing-box")
  ura.api.spawn("mygo -p 4611 $HOME/.config/ura/assets/catppuccin-homepage")
  ura.api.spawn("mako")
  ura.api.spawn("otd-daemon")
  ura.api.spawn("fcitx5 -rd")
  ura.api.spawn("wl-clip-persist -c both --reconnect-tries 3")
  -- ura.api.spawn([[joystickwake --command 'uracil -c "ura.api.notify_idle_activity()"']])
  ura.api.spawn(
    [[swayidle -w timeout 10 'uracil ~/.config/ura/scripts/hide_cursor.lua' resume 'uracil ~/.config/ura/scripts/hide_cursor.lua -t']])
  ura.api.spawn("ddcmod --init")
  ura.input.keyboard.set_repeat(40, 300)
  ura.input.cursor.set_theme({ size = 18 })
end)

ura.hook.set("reload", function()
  ura.input.keyboard.set_repeat(40, 300)
  ura.input.cursor.set_theme({ size = 18 })
end)

ura.hook.set("focus-change", function()
  ura.api.spawn("pkill -SIGRTMIN+9 waybar")
  ura.api.spawn("pkill -SIGRTMIN+10 waybar")
end)

ura.hook.set("workspace-change", function()
  ura.api.spawn("pkill -SIGRTMIN+8 waybar")
end)

ura.hook.set("window-app_id-change", function()
  ura.api.spawn("pkill -SIGRTMIN+9 waybar")
end)

ura.hook.set("window-title-change", function()
  ura.api.spawn("pkill -SIGRTMIN+10 waybar")
end)

ura.hook.set("new-input", function(name)
  ura.api.notify("new-input", name)
end)
